import { PRODUCT_ENTITLEMENT_KEYS } from "./product-entitlement-keys";

/**
 * Maps the `module` string used by <ModuleGuard module="..."> and Sidebar
 * to the corresponding PRODUCT_ENTITLEMENT_KEY checked by the backend
 * PlanEntitlementGuard.
 */
export const MODULE_TO_ENTITLEMENT: Record<string, string> = {
  dashboard: PRODUCT_ENTITLEMENT_KEYS.MODULE_DASHBOARD,
  sales: PRODUCT_ENTITLEMENT_KEYS.MODULE_SALES,
  inventory: PRODUCT_ENTITLEMENT_KEYS.MODULE_INVENTORY,
  patients: PRODUCT_ENTITLEMENT_KEYS.MODULE_PATIENTS,
  prescriptions: PRODUCT_ENTITLEMENT_KEYS.MODULE_PRESCRIPTIONS,
  vaccination: PRODUCT_ENTITLEMENT_KEYS.MODULE_VACCINATION,
  delivery: PRODUCT_ENTITLEMENT_KEYS.MODULE_DELIVERY,
  billing: PRODUCT_ENTITLEMENT_KEYS.MODULE_BILLING_OPERATIONS,
  accounting: PRODUCT_ENTITLEMENT_KEYS.MODULE_ACCOUNTING,
  suppliers: PRODUCT_ENTITLEMENT_KEYS.MODULE_SUPPLIERS,
  "supply-chain": PRODUCT_ENTITLEMENT_KEYS.MODULE_SUPPLY_CHAIN,
  quality: PRODUCT_ENTITLEMENT_KEYS.MODULE_QUALITY,
  insurance: PRODUCT_ENTITLEMENT_KEYS.MODULE_INSURANCE,
  "e-invoice": PRODUCT_ENTITLEMENT_KEYS.MODULE_E_INVOICE,
  hr: PRODUCT_ENTITLEMENT_KEYS.MODULE_HR,
  analytics: PRODUCT_ENTITLEMENT_KEYS.MODULE_ANALYTICS,
  reports: PRODUCT_ENTITLEMENT_KEYS.MODULE_REPORTS,
  notifications: PRODUCT_ENTITLEMENT_KEYS.MODULE_NOTIFICATIONS,
  loyalty: PRODUCT_ENTITLEMENT_KEYS.MODULE_LOYALTY,
  "customers-b2b": PRODUCT_ENTITLEMENT_KEYS.MODULE_CUSTOMERS_B2B,
  "sales-orders-b2b": PRODUCT_ENTITLEMENT_KEYS.MODULE_SALES_ORDERS_B2B,
  "credit-desk": PRODUCT_ENTITLEMENT_KEYS.MODULE_CREDIT_CONTROL,
  "returns-rma": PRODUCT_ENTITLEMENT_KEYS.MODULE_RETURNS_RMA,
  "pricing-desk": PRODUCT_ENTITLEMENT_KEYS.MODULE_PRICING_DESK,
  "ap-matching": PRODUCT_ENTITLEMENT_KEYS.MODULE_AP_MATCHING,
  "b2b-dashboard": PRODUCT_ENTITLEMENT_KEYS.MODULE_B2B_DASHBOARD,
  "b2b-governance": PRODUCT_ENTITLEMENT_KEYS.MODULE_B2B_GOVERNANCE,
  "b2b-async": PRODUCT_ENTITLEMENT_KEYS.MODULE_B2B_ASYNC,
  "b2b-integrations": PRODUCT_ENTITLEMENT_KEYS.MODULE_B2B_INTEGRATIONS,
  "audit-events": PRODUCT_ENTITLEMENT_KEYS.MODULE_COMPLIANCE_AUDIT,
  compliance: PRODUCT_ENTITLEMENT_KEYS.MODULE_COMPLIANCE_AUDIT,
  settings: PRODUCT_ENTITLEMENT_KEYS.MODULE_SETTINGS,
  "document-sequences": PRODUCT_ENTITLEMENT_KEYS.MODULE_DOCUMENT_SEQUENCES,
  "document-templates": PRODUCT_ENTITLEMENT_KEYS.MODULE_DOCUMENT_TEMPLATES,
};
