/**
 * Permissions du système — Miroir exact du backend
 * Source: src/identity/domain/enums/permissions.enum.ts
 *
 * Format: {module}:{action}
 */

export enum Permission {
  // Accounting
  ACCOUNTING_READ = 'accounting:read',
  ACCOUNTING_WRITE = 'accounting:write',
  ACCOUNTS_CREATE = 'accounts:create',
  ACCOUNTS_READ = 'accounts:read',
  ACCOUNTS_UPDATE = 'accounts:update',
  ACCOUNTS_DELETE = 'accounts:delete',
  BANK_ACCOUNTS_CREATE = 'bank_accounts:create',
  BANK_ACCOUNTS_READ = 'bank_accounts:read',
  BANK_ACCOUNTS_UPDATE = 'bank_accounts:update',
  BANK_ACCOUNTS_DELETE = 'bank_accounts:delete',
  BANK_TRANSACTIONS_CREATE = 'bank_transactions:create',
  BANK_TRANSACTIONS_READ = 'bank_transactions:read',
  BANK_TRANSACTIONS_UPDATE = 'bank_transactions:update',
  BUDGETS_CREATE = 'budgets:create',
  BUDGETS_READ = 'budgets:read',
  BUDGETS_UPDATE = 'budgets:update',
  BUDGETS_DELETE = 'budgets:delete',
  EXPENSES_CREATE = 'expenses:create',
  EXPENSES_READ = 'expenses:read',
  EXPENSES_UPDATE = 'expenses:update',
  EXPENSES_DELETE = 'expenses:delete',
  FINANCIAL_PERIODS_CREATE = 'financial_periods:create',
  FINANCIAL_PERIODS_READ = 'financial_periods:read',
  FINANCIAL_PERIODS_UPDATE = 'financial_periods:update',
  FINANCIAL_REPORTS_READ = 'financial_reports:read',
  JOURNAL_ENTRIES_CREATE = 'journal_entries:create',
  TAX_RATES_CREATE = 'tax_rates:create',
  TAX_RATES_READ = 'tax_rates:read',
  TAX_RATES_UPDATE = 'tax_rates:update',
  TAX_RATES_DELETE = 'tax_rates:delete',
  TRANSACTIONS_CREATE = 'transactions:create',
  TRANSACTIONS_READ = 'transactions:read',
  TRANSACTIONS_UPDATE = 'transactions:update',

  // Inventory Alerts
  INVENTORY_ALERTS_CREATE = 'inventory_alerts:create',
  INVENTORY_ALERTS_READ = 'inventory_alerts:read',
  INVENTORY_ALERTS_UPDATE = 'inventory_alerts:update',
  INVENTORY_ALERTS_DELETE = 'inventory_alerts:delete',

  // Inventory
  INVENTORY_ITEMS_READ = 'inventory_items:read',
  INVENTORY_COUNTS_CREATE = 'inventory_counts:create',
  INVENTORY_COUNTS_READ = 'inventory_counts:read',
  INVENTORY_COUNTS_UPDATE = 'inventory_counts:update',
  INVENTORY_EVENTS_CREATE = 'inventory_events:create',
  INVENTORY_EVENTS_READ = 'inventory_events:read',
  INVENTORY_LOCATIONS_CREATE = 'inventory_locations:create',
  INVENTORY_LOCATIONS_READ = 'inventory_locations:read',
  INVENTORY_LOCATIONS_UPDATE = 'inventory_locations:update',
  INVENTORY_POLICIES_CREATE = 'inventory_policies:create',
  INVENTORY_POLICIES_READ = 'inventory_policies:read',
  INVENTORY_POLICIES_UPDATE = 'inventory_policies:update',
  INVENTORY_RESERVATIONS_CREATE = 'inventory_reservations:create',
  INVENTORY_RESERVATIONS_READ = 'inventory_reservations:read',
  INVENTORY_RESERVATIONS_UPDATE = 'inventory_reservations:update',
  INVENTORY_TRANSACTIONS_CREATE = 'inventory_transactions:create',
  INVENTORY_TRANSACTIONS_READ = 'inventory_transactions:read',
  STOCK_TRANSFERS_CREATE = 'stock_transfers:create',
  STOCK_TRANSFERS_READ = 'stock_transfers:read',
  STOCK_TRANSFERS_UPDATE = 'stock_transfers:update',

  // Products
  PRODUCTS_CREATE = 'products:create',
  PRODUCTS_READ = 'products:read',
  PRODUCTS_UPDATE = 'products:update',
  PRODUCTS_DELETE = 'products:delete',
  PRODUCT_BATCHES_CREATE = 'product_batches:create',
  PRODUCT_BATCHES_READ = 'product_batches:read',
  PRODUCT_BATCHES_UPDATE = 'product_batches:update',
  ORGANIZATION_PRODUCT_PRICES_CREATE = 'organization_product_prices:create',
  ORGANIZATION_PRODUCT_PRICES_READ = 'organization_product_prices:read',
  ORGANIZATION_PRODUCT_PRICES_UPDATE = 'organization_product_prices:update',
  ORGANIZATION_PRODUCT_PRICES_DELETE = 'organization_product_prices:delete',
  BATCH_RECALLS_CREATE = 'batch_recalls:create',
  BATCH_RECALLS_READ = 'batch_recalls:read',
  BATCH_RECALLS_UPDATE = 'batch_recalls:update',
  CONTROLLED_SUBSTANCE_LOGS_CREATE = 'controlled_substance_logs:create',
  CONTROLLED_SUBSTANCE_LOGS_READ = 'controlled_substance_logs:read',

  // Sales
  SALES_CREATE = 'sales:create',
  SALES_READ = 'sales:read',
  SALES_UPDATE = 'sales:update',
  INVOICES_CREATE = 'invoices:create',
  INVOICES_READ = 'invoices:read',
  INVOICES_UPDATE = 'invoices:update',
  INVOICES_DELETE = 'invoices:delete',

  // Payments
  PAYMENTS_CREATE = 'payments:create',
  PAYMENTS_READ = 'payments:read',
  PAYMENTS_UPDATE = 'payments:update',
  PAYMENTS_DELETE = 'payments:delete',

  // Patients
  PATIENTS_READ = 'patients:read',
  PATIENTS_WRITE = 'patients:write',

  // Prescriptions
  PRESCRIPTIONS_READ = 'prescriptions:read',
  PRESCRIPTIONS_WRITE = 'prescriptions:write',

  // Suppliers
  SUPPLIERS_CREATE = 'suppliers:create',
  SUPPLIERS_READ = 'suppliers:read',
  SUPPLIERS_UPDATE = 'suppliers:update',
  SUPPLIERS_DELETE = 'suppliers:delete',
  SUPPLIER_PERFORMANCE_CREATE = 'supplier_performance:create',
  SUPPLIER_PERFORMANCE_READ = 'supplier_performance:read',
  SUPPLIER_PERFORMANCE_UPDATE = 'supplier_performance:update',

  // Supply Chain
  SUPPLY_CHAIN_READ = 'supply_chain:read',
  SUPPLY_CHAIN_UPDATE = 'supply_chain:update',
  SUPPLY_CHAIN_ALERTS_CREATE = 'supply_chain_alerts:create',
  SUPPLY_CHAIN_ALERTS_READ = 'supply_chain_alerts:read',
  SUPPLY_CHAIN_ALERTS_UPDATE = 'supply_chain_alerts:update',
  PURCHASE_ORDERS_CREATE = 'purchase_orders:create',
  PURCHASE_ORDERS_READ = 'purchase_orders:read',
  PURCHASE_ORDERS_UPDATE = 'purchase_orders:update',
  DEMAND_FORECASTS_CREATE = 'demand_forecasts:create',
  DEMAND_FORECASTS_READ = 'demand_forecasts:read',
  DEMAND_FORECASTS_UPDATE = 'demand_forecasts:update',

  // Vaccination
  VACCINATION_READ = 'vaccination:read',
  VACCINATION_WRITE = 'vaccination:write',

  // Quality
  QUALITY_EVENTS_CREATE = 'quality_events:create',
  QUALITY_EVENTS_READ = 'quality_events:read',
  QUALITY_EVENTS_UPDATE = 'quality_events:update',
  QUALITY_EVENTS_DELETE = 'quality_events:delete',
  QUALITY_CAPAS_CREATE = 'quality_capas:create',
  QUALITY_CAPAS_READ = 'quality_capas:read',
  QUALITY_CAPAS_UPDATE = 'quality_capas:update',
  QUALITY_DOCUMENTS_CREATE = 'quality_documents:create',
  QUALITY_DOCUMENTS_READ = 'quality_documents:read',
  QUALITY_DOCUMENTS_UPDATE = 'quality_documents:update',
  QUALITY_METRICS_CREATE = 'quality_metrics:create',
  QUALITY_METRICS_READ = 'quality_metrics:read',
  QUALITY_METRICS_UPDATE = 'quality_metrics:update',
  QUALITY_TRAINING_CREATE = 'quality_training:create',
  QUALITY_TRAINING_READ = 'quality_training:read',
  QUALITY_TRAINING_UPDATE = 'quality_training:update',

  // Insurance
  INSURANCE_PROVIDERS_CREATE = 'insurance_providers:create',
  INSURANCE_PROVIDERS_READ = 'insurance_providers:read',
  INSURANCE_PROVIDERS_UPDATE = 'insurance_providers:update',
  INSURANCE_PROVIDERS_DELETE = 'insurance_providers:delete',

  // HR
  EMPLOYEES_CREATE = 'employees:create',
  EMPLOYEES_READ = 'employees:read',
  EMPLOYEES_UPDATE = 'employees:update',
  EMPLOYEES_DELETE = 'employees:delete',
  SHIFTS_CREATE = 'shifts:create',
  SHIFTS_READ = 'shifts:read',
  SHIFTS_UPDATE = 'shifts:update',
  SHIFTS_DELETE = 'shifts:delete',
  ATTENDANCE_CREATE = 'attendance:create',
  ATTENDANCE_READ = 'attendance:read',
  ATTENDANCE_UPDATE = 'attendance:update',
  LEAVES_CREATE = 'leaves:create',
  LEAVES_READ = 'leaves:read',
  LEAVES_UPDATE = 'leaves:update',
  LEAVES_APPROVE = 'leaves:approve',
  PAYROLL_CREATE = 'payroll:create',
  PAYROLL_READ = 'payroll:read',
  PAYROLL_UPDATE = 'payroll:update',
  PAYROLL_APPROVE = 'payroll:approve',
  HR_DOCUMENTS_CREATE = 'hr_documents:create',
  HR_DOCUMENTS_READ = 'hr_documents:read',
  HR_DOCUMENTS_UPDATE = 'hr_documents:update',
  HR_DOCUMENTS_DELETE = 'hr_documents:delete',
  EVALUATIONS_CREATE = 'evaluations:create',
  EVALUATIONS_READ = 'evaluations:read',
  EVALUATIONS_UPDATE = 'evaluations:update',

  // Delivery
  DELIVERY_CREATE = 'delivery:create',
  DELIVERY_READ = 'delivery:read',
  DELIVERY_UPDATE = 'delivery:update',
  DELIVERY_DELETE = 'delivery:delete',

  // BI / Analytics
  BI_READ = 'bi:read',
  BI_WRITE = 'bi:write',
  ANALYTICS_READ = 'analytics:read',

  // Fiscal / E-Invoice
  FISCAL_CREDENTIALS_READ = 'fiscal:credentials:read',
  FISCAL_CREDENTIALS_WRITE = 'fiscal:credentials:write',
  FISCAL_INVOICES_READ = 'fiscal:invoices:read',
  FISCAL_INVOICES_SUBMIT = 'fiscal:invoices:submit',
  FISCAL_INVOICES_CANCEL = 'fiscal:invoices:cancel',
  FISCAL_INVOICES_RETRY = 'fiscal:invoices:retry',
  FISCAL_REPORTS_READ = 'fiscal:reports:read',
  FISCAL_AUDIT_READ = 'fiscal:audit:read',

  /** Journal métier / compliance (tenant) */
  TENANT_AUDIT_READ = 'tenant_audit:read',

  /** CRM / fidélité (tenant pharmacie) */
  LOYALTY_READ = 'loyalty:read',
  LOYALTY_WRITE = 'loyalty:write',

  // B2B
  BUSINESS_PARTNERS_CREATE = 'business_partners:create',
  BUSINESS_PARTNERS_READ = 'business_partners:read',
  BUSINESS_PARTNERS_UPDATE = 'business_partners:update',
  BUSINESS_PARTNERS_DELETE = 'business_partners:delete',
  SALES_ORDERS_B2B_CREATE = 'sales_orders_b2b:create',
  SALES_ORDERS_B2B_READ = 'sales_orders_b2b:read',
  SALES_ORDERS_B2B_UPDATE = 'sales_orders_b2b:update',
  SALES_ORDERS_B2B_DELETE = 'sales_orders_b2b:delete',
  CREDIT_CONTROL_READ = 'credit_control:read',
  CREDIT_CONTROL_WRITE = 'credit_control:write',
  COMMERCIAL_TERMS_READ = 'commercial_terms:read',
  COMMERCIAL_TERMS_WRITE = 'commercial_terms:write',
  RETURNS_RMA_READ = 'returns_rma:read',
  RETURNS_RMA_WRITE = 'returns_rma:write',
  AP_MATCHING_READ = 'ap_matching:read',
  AP_MATCHING_WRITE = 'ap_matching:write',
  B2B_DASHBOARD_READ = 'b2b_dashboard:read',
  B2B_OVERRIDES_REQUEST = 'b2b_overrides:request',
  B2B_OVERRIDES_APPROVE = 'b2b_overrides:approve',
  B2B_ASYNC_JOBS_READ = 'b2b_async_jobs:read',
  B2B_ASYNC_JOBS_WRITE = 'b2b_async_jobs:write',
  B2B_INTEGRATIONS_READ = 'b2b_integrations:read',
  B2B_INTEGRATIONS_WRITE = 'b2b_integrations:write',

  // Roles
  ROLES_CREATE = 'roles:create',
  ROLES_READ = 'roles:read',
  ROLES_UPDATE = 'roles:update',
  ROLES_DELETE = 'roles:delete',
  ROLES_ASSIGN = 'roles:assign',

  // Notifications
  NOTIFICATIONS_READ = 'notifications:read',
  NOTIFICATIONS_WRITE = 'notifications:write',
}

export const PermissionGroups = {
  ACCOUNTING: [
    Permission.ACCOUNTING_READ, Permission.ACCOUNTING_WRITE,
    Permission.ACCOUNTS_CREATE, Permission.ACCOUNTS_READ,
    Permission.BANK_ACCOUNTS_CREATE, Permission.BANK_ACCOUNTS_READ,
    Permission.BANK_ACCOUNTS_UPDATE, Permission.BANK_ACCOUNTS_DELETE,
    Permission.BANK_TRANSACTIONS_CREATE, Permission.BANK_TRANSACTIONS_READ,
    Permission.BANK_TRANSACTIONS_UPDATE,
    Permission.BUDGETS_CREATE, Permission.BUDGETS_READ,
    Permission.BUDGETS_UPDATE, Permission.BUDGETS_DELETE,
    Permission.EXPENSES_CREATE, Permission.EXPENSES_READ,
    Permission.EXPENSES_UPDATE, Permission.EXPENSES_DELETE,
    Permission.FINANCIAL_PERIODS_CREATE, Permission.FINANCIAL_PERIODS_READ,
    Permission.FINANCIAL_PERIODS_UPDATE, Permission.FINANCIAL_REPORTS_READ,
    Permission.JOURNAL_ENTRIES_CREATE,
    Permission.TAX_RATES_CREATE, Permission.TAX_RATES_READ,
    Permission.TAX_RATES_UPDATE, Permission.TAX_RATES_DELETE,
    Permission.TRANSACTIONS_CREATE, Permission.TRANSACTIONS_READ,
    Permission.TRANSACTIONS_UPDATE,
  ],
  INVENTORY: [
    Permission.INVENTORY_ITEMS_READ,
    Permission.INVENTORY_ALERTS_CREATE, Permission.INVENTORY_ALERTS_READ,
    Permission.INVENTORY_ALERTS_UPDATE,
    Permission.INVENTORY_COUNTS_CREATE, Permission.INVENTORY_COUNTS_READ,
    Permission.INVENTORY_COUNTS_UPDATE,
    Permission.INVENTORY_EVENTS_CREATE, Permission.INVENTORY_EVENTS_READ,
    Permission.INVENTORY_LOCATIONS_CREATE, Permission.INVENTORY_LOCATIONS_READ,
    Permission.INVENTORY_LOCATIONS_UPDATE,
    Permission.INVENTORY_POLICIES_CREATE, Permission.INVENTORY_POLICIES_READ,
    Permission.INVENTORY_POLICIES_UPDATE,
    Permission.INVENTORY_RESERVATIONS_CREATE, Permission.INVENTORY_RESERVATIONS_READ,
    Permission.INVENTORY_RESERVATIONS_UPDATE,
    Permission.INVENTORY_TRANSACTIONS_CREATE, Permission.INVENTORY_TRANSACTIONS_READ,
    Permission.STOCK_TRANSFERS_CREATE, Permission.STOCK_TRANSFERS_READ,
    Permission.STOCK_TRANSFERS_UPDATE,
  ],
  PRODUCTS: [
    Permission.PRODUCTS_CREATE, Permission.PRODUCTS_READ,
    Permission.PRODUCTS_UPDATE, Permission.PRODUCTS_DELETE,
    Permission.PRODUCT_BATCHES_CREATE, Permission.PRODUCT_BATCHES_READ,
    Permission.PRODUCT_BATCHES_UPDATE,
    Permission.ORGANIZATION_PRODUCT_PRICES_CREATE, Permission.ORGANIZATION_PRODUCT_PRICES_READ,
    Permission.ORGANIZATION_PRODUCT_PRICES_UPDATE, Permission.ORGANIZATION_PRODUCT_PRICES_DELETE,
    Permission.BATCH_RECALLS_CREATE, Permission.BATCH_RECALLS_READ,
    Permission.BATCH_RECALLS_UPDATE,
    Permission.CONTROLLED_SUBSTANCE_LOGS_CREATE, Permission.CONTROLLED_SUBSTANCE_LOGS_READ,
  ],
  SALES: [
    Permission.SALES_CREATE, Permission.SALES_READ, Permission.SALES_UPDATE,
    Permission.INVOICES_CREATE, Permission.INVOICES_READ,
    Permission.INVOICES_UPDATE, Permission.INVOICES_DELETE,
  ],
  PAYMENTS: [
    Permission.PAYMENTS_CREATE, Permission.PAYMENTS_READ,
    Permission.PAYMENTS_UPDATE, Permission.PAYMENTS_DELETE,
  ],
  PATIENTS: [Permission.PATIENTS_READ, Permission.PATIENTS_WRITE],
  PRESCRIPTIONS: [Permission.PRESCRIPTIONS_READ, Permission.PRESCRIPTIONS_WRITE],
  SUPPLIERS: [
    Permission.SUPPLIERS_CREATE, Permission.SUPPLIERS_READ,
    Permission.SUPPLIERS_UPDATE, Permission.SUPPLIERS_DELETE,
    Permission.SUPPLIER_PERFORMANCE_CREATE, Permission.SUPPLIER_PERFORMANCE_READ,
    Permission.SUPPLIER_PERFORMANCE_UPDATE,
  ],
  SUPPLY_CHAIN: [
    Permission.SUPPLY_CHAIN_READ, Permission.SUPPLY_CHAIN_UPDATE,
    Permission.SUPPLY_CHAIN_ALERTS_CREATE, Permission.SUPPLY_CHAIN_ALERTS_READ,
    Permission.SUPPLY_CHAIN_ALERTS_UPDATE,
    Permission.PURCHASE_ORDERS_CREATE, Permission.PURCHASE_ORDERS_READ,
    Permission.PURCHASE_ORDERS_UPDATE,
    Permission.DEMAND_FORECASTS_CREATE, Permission.DEMAND_FORECASTS_READ,
    Permission.DEMAND_FORECASTS_UPDATE,
  ],
  VACCINATION: [Permission.VACCINATION_READ, Permission.VACCINATION_WRITE],
  QUALITY: [
    Permission.QUALITY_EVENTS_CREATE, Permission.QUALITY_EVENTS_READ,
    Permission.QUALITY_EVENTS_UPDATE, Permission.QUALITY_EVENTS_DELETE,
    Permission.QUALITY_CAPAS_CREATE, Permission.QUALITY_CAPAS_READ,
    Permission.QUALITY_CAPAS_UPDATE,
    Permission.QUALITY_DOCUMENTS_CREATE, Permission.QUALITY_DOCUMENTS_READ,
    Permission.QUALITY_DOCUMENTS_UPDATE,
    Permission.QUALITY_METRICS_CREATE, Permission.QUALITY_METRICS_READ,
    Permission.QUALITY_METRICS_UPDATE,
    Permission.QUALITY_TRAINING_CREATE, Permission.QUALITY_TRAINING_READ,
    Permission.QUALITY_TRAINING_UPDATE,
  ],
  INSURANCE: [
    Permission.INSURANCE_PROVIDERS_CREATE, Permission.INSURANCE_PROVIDERS_READ,
    Permission.INSURANCE_PROVIDERS_UPDATE, Permission.INSURANCE_PROVIDERS_DELETE,
  ],
  HR: [
    Permission.EMPLOYEES_CREATE, Permission.EMPLOYEES_READ,
    Permission.EMPLOYEES_UPDATE, Permission.EMPLOYEES_DELETE,
    Permission.SHIFTS_CREATE, Permission.SHIFTS_READ,
    Permission.SHIFTS_UPDATE, Permission.SHIFTS_DELETE,
    Permission.ATTENDANCE_CREATE, Permission.ATTENDANCE_READ,
    Permission.ATTENDANCE_UPDATE,
    Permission.LEAVES_CREATE, Permission.LEAVES_READ,
    Permission.LEAVES_UPDATE, Permission.LEAVES_APPROVE,
    Permission.PAYROLL_CREATE, Permission.PAYROLL_READ,
    Permission.PAYROLL_UPDATE, Permission.PAYROLL_APPROVE,
    Permission.HR_DOCUMENTS_CREATE, Permission.HR_DOCUMENTS_READ,
    Permission.HR_DOCUMENTS_UPDATE, Permission.HR_DOCUMENTS_DELETE,
    Permission.EVALUATIONS_CREATE, Permission.EVALUATIONS_READ,
    Permission.EVALUATIONS_UPDATE,
  ],
  DELIVERY: [
    Permission.DELIVERY_CREATE, Permission.DELIVERY_READ,
    Permission.DELIVERY_UPDATE, Permission.DELIVERY_DELETE,
  ],
  BI: [Permission.BI_READ, Permission.BI_WRITE, Permission.ANALYTICS_READ],
  FISCAL: [
    Permission.FISCAL_CREDENTIALS_READ, Permission.FISCAL_CREDENTIALS_WRITE,
    Permission.FISCAL_INVOICES_READ, Permission.FISCAL_INVOICES_SUBMIT,
    Permission.FISCAL_INVOICES_CANCEL, Permission.FISCAL_INVOICES_RETRY,
    Permission.FISCAL_REPORTS_READ, Permission.FISCAL_AUDIT_READ,
  ],
  ROLES: [
    Permission.ROLES_CREATE, Permission.ROLES_READ,
    Permission.ROLES_UPDATE, Permission.ROLES_DELETE,
    Permission.ROLES_ASSIGN,
  ],
  COMPLIANCE_AUDIT: [Permission.TENANT_AUDIT_READ],
  CRM_LOYALTY: [Permission.LOYALTY_READ, Permission.LOYALTY_WRITE],
  NOTIFICATIONS: [Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE],
} as const;

export const ALL_PERMISSIONS = Object.values(Permission);

/**
 * Mapping module sidebar → permissions requises pour l'accès
 */
export const MODULE_PERMISSIONS: Record<string, Permission[]> = {
  dashboard: [],
  sales: [Permission.SALES_READ],
  inventory: [Permission.INVENTORY_ITEMS_READ, Permission.PRODUCTS_READ],
  patients: [Permission.PATIENTS_READ],
  prescriptions: [Permission.PRESCRIPTIONS_READ],
  accounting: [Permission.ACCOUNTING_READ],
  billing: [Permission.INVOICES_READ],
  hr: [Permission.EMPLOYEES_READ],
  suppliers: [Permission.SUPPLIERS_READ],
  'supply-chain': [Permission.SUPPLY_CHAIN_READ, Permission.PURCHASE_ORDERS_READ],
  'purchase-orders': [Permission.PURCHASE_ORDERS_READ],
  quality: [Permission.QUALITY_EVENTS_READ],
  vaccination: [Permission.VACCINATION_READ],
  delivery: [Permission.DELIVERY_READ],
  analytics: [Permission.BI_READ, Permission.ANALYTICS_READ],
  notifications: [Permission.NOTIFICATIONS_READ],
  insurance: [Permission.INSURANCE_PROVIDERS_READ],
  'e-invoice': [Permission.FISCAL_INVOICES_READ],
  settings: [Permission.ROLES_READ],
  'audit-events': [Permission.TENANT_AUDIT_READ],
  loyalty: [Permission.LOYALTY_READ],
  'customers-b2b': [Permission.BUSINESS_PARTNERS_READ],
  'sales-orders-b2b': [Permission.SALES_ORDERS_B2B_READ],
  'credit-desk': [Permission.CREDIT_CONTROL_READ],
  'pricing-desk': [Permission.COMMERCIAL_TERMS_READ],
  'returns-rma': [Permission.RETURNS_RMA_READ],
  'ap-matching': [Permission.AP_MATCHING_READ],
  'b2b-dashboard': [Permission.B2B_DASHBOARD_READ],
  'b2b-governance': [Permission.B2B_OVERRIDES_REQUEST],
  'b2b-async': [Permission.B2B_ASYNC_JOBS_READ],
  'b2b-integrations': [Permission.B2B_INTEGRATIONS_READ],
  profile: [],
};
