/**
 * Rôles du système — Miroir exact du backend
 * Source: src/identity/domain/enums/roles.enum.ts
 */

import { Permission, PermissionGroups } from './permissions';

export enum Role {
  SUPER_ADMIN = 'super_admin',
  PLATFORM_ADMIN = 'platform_admin',
  TENANT_OWNER = 'tenant_owner',
  TENANT_ADMIN = 'tenant_admin',
  TENANT_MANAGER = 'tenant_manager',
  PHARMACY_OWNER = 'pharmacy_owner',
  PHARMACY_MANAGER = 'pharmacy_manager',
  PHARMACIST = 'pharmacist',
  PHARMACY_ASSISTANT = 'pharmacy_assistant',
  PHARMACY_TECHNICIAN = 'pharmacy_technician',
  CASHIER = 'cashier',
  DOCTOR = 'doctor',
  NURSE = 'nurse',
  ACCOUNTANT = 'accountant',
  HR_MANAGER = 'hr_manager',
  INVENTORY_MANAGER = 'inventory_manager',
  SALES_MANAGER = 'sales_manager',
  QUALITY_MANAGER = 'quality_manager',
  SUPPLY_CHAIN_MANAGER = 'supply_chain_manager',
  PATIENT = 'patient',
  STAFF_MEMBER = 'staff_member',
  USER = 'user',
  GUEST = 'guest',
}

export const ROLE_LABELS: Record<Role, string> = {
  [Role.SUPER_ADMIN]: 'Super Administrateur',
  [Role.PLATFORM_ADMIN]: 'Admin Plateforme',
  [Role.TENANT_OWNER]: 'Propriétaire',
  [Role.TENANT_ADMIN]: 'Administrateur',
  [Role.TENANT_MANAGER]: 'Manager',
  [Role.PHARMACY_OWNER]: 'Propriétaire Pharmacie',
  [Role.PHARMACY_MANAGER]: 'Gérant Pharmacie',
  [Role.PHARMACIST]: 'Pharmacien',
  [Role.PHARMACY_ASSISTANT]: 'Assistant Pharmacien',
  [Role.PHARMACY_TECHNICIAN]: 'Technicien',
  [Role.CASHIER]: 'Caissier',
  [Role.DOCTOR]: 'Médecin',
  [Role.NURSE]: 'Infirmier',
  [Role.ACCOUNTANT]: 'Comptable',
  [Role.HR_MANAGER]: 'Responsable RH',
  [Role.INVENTORY_MANAGER]: 'Gestionnaire Stock',
  [Role.SALES_MANAGER]: 'Responsable Ventes',
  [Role.QUALITY_MANAGER]: 'Responsable Qualité',
  [Role.SUPPLY_CHAIN_MANAGER]: 'Responsable Supply Chain',
  [Role.PATIENT]: 'Patient',
  [Role.STAFF_MEMBER]: 'Membre du Personnel',
  [Role.USER]: 'Utilisateur',
  [Role.GUEST]: 'Invité',
};

export const RoleHierarchy: Record<Role, number> = {
  [Role.SUPER_ADMIN]: 1000,
  [Role.PLATFORM_ADMIN]: 900,
  [Role.TENANT_OWNER]: 800,
  [Role.TENANT_ADMIN]: 700,
  [Role.TENANT_MANAGER]: 600,
  [Role.PHARMACY_OWNER]: 550,
  [Role.PHARMACY_MANAGER]: 500,
  [Role.PHARMACIST]: 400,
  [Role.PHARMACY_ASSISTANT]: 350,
  [Role.PHARMACY_TECHNICIAN]: 300,
  [Role.CASHIER]: 250,
  [Role.DOCTOR]: 400,
  [Role.NURSE]: 350,
  [Role.ACCOUNTANT]: 450,
  [Role.HR_MANAGER]: 450,
  [Role.INVENTORY_MANAGER]: 450,
  [Role.SALES_MANAGER]: 450,
  [Role.QUALITY_MANAGER]: 450,
  [Role.SUPPLY_CHAIN_MANAGER]: 450,
  [Role.STAFF_MEMBER]: 200,
  [Role.PATIENT]: 100,
  [Role.USER]: 50,
  [Role.GUEST]: 10,
};

/**
 * Mapping rôle → permissions — Miroir exact du backend RolePermissions
 */
export const ROLE_PERMISSION_MAP: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Object.values(Permission),
  [Role.PLATFORM_ADMIN]: Object.values(Permission),
  [Role.TENANT_OWNER]: Object.values(Permission),

  [Role.TENANT_ADMIN]: [
    ...PermissionGroups.ACCOUNTING,
    ...PermissionGroups.INVENTORY,
    ...PermissionGroups.PRODUCTS,
    ...PermissionGroups.SALES,
    ...PermissionGroups.PAYMENTS,
    ...PermissionGroups.PATIENTS,
    ...PermissionGroups.PRESCRIPTIONS,
    ...PermissionGroups.SUPPLIERS,
    ...PermissionGroups.SUPPLY_CHAIN,
    ...PermissionGroups.VACCINATION,
    ...PermissionGroups.QUALITY,
    ...PermissionGroups.INSURANCE,
    ...PermissionGroups.HR,
    ...PermissionGroups.DELIVERY,
    ...PermissionGroups.BI,
    ...PermissionGroups.FISCAL,
    ...PermissionGroups.NOTIFICATIONS,
  ],

  [Role.TENANT_MANAGER]: [
    Permission.ACCOUNTING_READ, Permission.FINANCIAL_REPORTS_READ,
    ...PermissionGroups.INVENTORY,
    ...PermissionGroups.PRODUCTS,
    ...PermissionGroups.SALES,
    Permission.PAYMENTS_READ,
    ...PermissionGroups.PATIENTS,
    ...PermissionGroups.PRESCRIPTIONS,
    Permission.SUPPLIERS_READ,
    ...PermissionGroups.SUPPLY_CHAIN,
    ...PermissionGroups.VACCINATION,
    Permission.QUALITY_EVENTS_READ, Permission.QUALITY_METRICS_READ,
    ...PermissionGroups.NOTIFICATIONS,
  ],

  [Role.PHARMACY_OWNER]: [
    ...PermissionGroups.ACCOUNTING,
    ...PermissionGroups.INVENTORY,
    ...PermissionGroups.PRODUCTS,
    ...PermissionGroups.SALES,
    ...PermissionGroups.PAYMENTS,
    ...PermissionGroups.PATIENTS,
    ...PermissionGroups.PRESCRIPTIONS,
    ...PermissionGroups.SUPPLIERS,
    ...PermissionGroups.SUPPLY_CHAIN,
    ...PermissionGroups.VACCINATION,
    ...PermissionGroups.QUALITY,
    ...PermissionGroups.INSURANCE,
    ...PermissionGroups.HR,
    ...PermissionGroups.DELIVERY,
    ...PermissionGroups.BI,
    ...PermissionGroups.FISCAL,
    ...PermissionGroups.NOTIFICATIONS,
  ],

  [Role.PHARMACY_MANAGER]: [
    Permission.ACCOUNTING_READ, Permission.FINANCIAL_REPORTS_READ,
    ...PermissionGroups.INVENTORY,
    ...PermissionGroups.PRODUCTS,
    ...PermissionGroups.SALES,
    Permission.PAYMENTS_READ, Permission.PAYMENTS_CREATE,
    ...PermissionGroups.PATIENTS,
    ...PermissionGroups.PRESCRIPTIONS,
    Permission.SUPPLIERS_READ,
    Permission.PURCHASE_ORDERS_CREATE, Permission.PURCHASE_ORDERS_READ,
    Permission.PURCHASE_ORDERS_UPDATE,
    ...PermissionGroups.VACCINATION,
    Permission.QUALITY_EVENTS_CREATE, Permission.QUALITY_EVENTS_READ,
    ...PermissionGroups.NOTIFICATIONS,
  ],

  [Role.PHARMACIST]: [
    Permission.INVENTORY_ITEMS_READ, Permission.INVENTORY_ALERTS_READ,
    Permission.PRODUCTS_READ, Permission.PRODUCT_BATCHES_READ,
    Permission.SALES_CREATE, Permission.SALES_READ, Permission.SALES_UPDATE,
    Permission.INVOICES_CREATE, Permission.INVOICES_READ,
    Permission.PAYMENTS_CREATE, Permission.PAYMENTS_READ,
    ...PermissionGroups.PATIENTS,
    ...PermissionGroups.PRESCRIPTIONS,
    ...PermissionGroups.VACCINATION,
    Permission.CONTROLLED_SUBSTANCE_LOGS_CREATE,
    Permission.CONTROLLED_SUBSTANCE_LOGS_READ,
    Permission.QUALITY_EVENTS_CREATE, Permission.QUALITY_EVENTS_READ,
    Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE,
  ],

  [Role.PHARMACY_ASSISTANT]: [
    Permission.INVENTORY_ITEMS_READ, Permission.INVENTORY_ALERTS_READ,
    Permission.PRODUCTS_READ, Permission.PRODUCT_BATCHES_READ,
    Permission.SALES_CREATE, Permission.SALES_READ,
    Permission.INVOICES_CREATE, Permission.INVOICES_READ,
    Permission.PAYMENTS_CREATE, Permission.PAYMENTS_READ,
    Permission.PATIENTS_READ, Permission.PATIENTS_WRITE,
    Permission.PRESCRIPTIONS_READ, Permission.PRESCRIPTIONS_WRITE,
    Permission.VACCINATION_READ, Permission.VACCINATION_WRITE,
    Permission.NOTIFICATIONS_READ,
  ],

  [Role.PHARMACY_TECHNICIAN]: [
    Permission.INVENTORY_ITEMS_READ,
    Permission.INVENTORY_COUNTS_CREATE, Permission.INVENTORY_COUNTS_READ,
    Permission.INVENTORY_TRANSACTIONS_CREATE, Permission.INVENTORY_TRANSACTIONS_READ,
    Permission.PRODUCTS_READ, Permission.PRODUCT_BATCHES_READ,
    Permission.STOCK_TRANSFERS_CREATE, Permission.STOCK_TRANSFERS_READ,
    Permission.PURCHASE_ORDERS_READ,
    Permission.NOTIFICATIONS_READ,
  ],

  [Role.CASHIER]: [
    Permission.PRODUCTS_READ,
    Permission.SALES_CREATE, Permission.SALES_READ,
    Permission.INVOICES_CREATE, Permission.INVOICES_READ,
    Permission.PAYMENTS_CREATE, Permission.PAYMENTS_READ,
    Permission.PATIENTS_READ,
    Permission.NOTIFICATIONS_READ,
  ],

  [Role.DOCTOR]: [
    Permission.PATIENTS_READ, Permission.PATIENTS_WRITE,
    Permission.PRESCRIPTIONS_READ, Permission.PRESCRIPTIONS_WRITE,
    Permission.VACCINATION_READ, Permission.VACCINATION_WRITE,
    Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE,
  ],

  [Role.NURSE]: [
    Permission.PATIENTS_READ, Permission.PATIENTS_WRITE,
    Permission.PRESCRIPTIONS_READ,
    Permission.VACCINATION_READ, Permission.VACCINATION_WRITE,
    Permission.NOTIFICATIONS_READ,
  ],

  [Role.ACCOUNTANT]: [
    ...PermissionGroups.ACCOUNTING,
    Permission.SALES_READ, Permission.INVOICES_READ, Permission.PAYMENTS_READ,
    Permission.EXPENSES_CREATE, Permission.EXPENSES_READ,
    Permission.EXPENSES_UPDATE, Permission.EXPENSES_DELETE,
    Permission.FISCAL_INVOICES_READ,
    Permission.FISCAL_REPORTS_READ, Permission.FISCAL_AUDIT_READ,
    Permission.NOTIFICATIONS_READ,
  ],

  [Role.HR_MANAGER]: [
    ...PermissionGroups.HR,
    Permission.EMPLOYEES_READ,
    Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE,
  ],

  [Role.INVENTORY_MANAGER]: [
    ...PermissionGroups.INVENTORY,
    ...PermissionGroups.PRODUCTS,
    Permission.SUPPLIERS_READ,
    ...PermissionGroups.SUPPLY_CHAIN,
    Permission.QUALITY_EVENTS_CREATE, Permission.QUALITY_EVENTS_READ,
    Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE,
  ],

  [Role.SALES_MANAGER]: [
    Permission.ACCOUNTING_READ, Permission.FINANCIAL_REPORTS_READ,
    Permission.INVENTORY_ITEMS_READ, Permission.PRODUCTS_READ,
    ...PermissionGroups.SALES,
    ...PermissionGroups.PAYMENTS,
    Permission.PATIENTS_READ,
    Permission.ORGANIZATION_PRODUCT_PRICES_CREATE,
    Permission.ORGANIZATION_PRODUCT_PRICES_READ,
    Permission.ORGANIZATION_PRODUCT_PRICES_UPDATE,
    Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE,
  ],

  [Role.QUALITY_MANAGER]: [
    ...PermissionGroups.QUALITY,
    Permission.INVENTORY_ITEMS_READ, Permission.PRODUCTS_READ,
    Permission.PRODUCT_BATCHES_READ,
    Permission.BATCH_RECALLS_CREATE, Permission.BATCH_RECALLS_READ,
    Permission.BATCH_RECALLS_UPDATE,
    Permission.CONTROLLED_SUBSTANCE_LOGS_READ,
    Permission.SUPPLIERS_READ,
    Permission.SUPPLIER_PERFORMANCE_CREATE, Permission.SUPPLIER_PERFORMANCE_READ,
    Permission.SUPPLIER_PERFORMANCE_UPDATE,
    Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE,
  ],

  [Role.SUPPLY_CHAIN_MANAGER]: [
    Permission.INVENTORY_ITEMS_READ, Permission.INVENTORY_ALERTS_READ,
    Permission.PRODUCTS_READ, Permission.PRODUCT_BATCHES_READ,
    ...PermissionGroups.SUPPLIERS,
    ...PermissionGroups.SUPPLY_CHAIN,
    Permission.QUALITY_EVENTS_READ,
    Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_WRITE,
  ],

  [Role.PATIENT]: [
    Permission.PRESCRIPTIONS_READ,
    Permission.VACCINATION_READ,
    Permission.NOTIFICATIONS_READ,
  ],

  [Role.STAFF_MEMBER]: [
    Permission.INVENTORY_ITEMS_READ, Permission.PRODUCTS_READ,
    Permission.PATIENTS_READ,
    Permission.NOTIFICATIONS_READ,
  ],

  [Role.USER]: [Permission.NOTIFICATIONS_READ],
  [Role.GUEST]: [Permission.NOTIFICATIONS_READ],
};
